language: generic

jobs:
  include:
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        install: 
          - pip install -r requirements.txt 
        script: 
          - python pythonconfiguration.py
          - python -m unittest box-20-21-team-f.services.rocket.test.rocketApiTest
