jobs:
  include:
      - language: python
      - stage: "Rocket Service units tests"
        name: "Units tests of rocket service"
        install: 
          - pip3 -r requirements.txt 
        script: python3 services/rocket/test/rocketApiTest.py
