language: generic

jobs:
  include:
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        before_install:
          - "pip install -U pip"
          - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
        install: 
          - pip install -r requirements.txt
        script:
          - python services/rocket/test/rocketApiTest.py
