language: generic

jobs:
  include:
      - stage: "Building and Launching"
        name: "Building all docker images and launching them"
        before_install:
          - chmod +x build.sh
          - chmod +x docker/CLIs/elon/build.sh
          - chmod +x docker/CLIs/tory/build.sh
          - chmod +x docker/CLIs/richard/build.sh
          - chmod +x docker/rpc/pollCreator/build.sh
          - chmod +x docker/services/rocketInventory/build.sh
          - chmod +x docker/services/weather/build.sh
          - chmod +x docker/services/launcher/build.sh
          - chmod +x launch.sh
          - chmod +x clean.sh
          - chmod +x stop.sh
          - chmod +x prepare.sh
        install: 
          - pip install -r requirements.txt
        script: 
          - ./prepare.sh
          - python services/rocketInventory/test/rocketApiTest.py
          - ./stop.sh
          - ./clean.sh
      # - stage: "Docker compose up"
      #   name: "Launch all docker containers"
      #   before_install:
      #     - chmod +x launch.sh
      #   script: ./launch.sh
      # - stage: "Rocket Service"
      #   name: "Units tests of rocket service"
      #   before_install:
      #     - "pip install -U pip"
      #     - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
      #   install: 
      #     - pip install -r requirements.txt
      #   script:
      #     - python services/rocketInventory/test/rocketApiTest.py
      # - stage: "Docker compose down"
      #   name: "Stop all docker containers"
      #   before_install:
      #     - chmod +x stop.sh
      #   script: ./stop.sh
      # - stage: "Clean up"
      #   before_install:
      #     - chmod +x clean.sh
      #   name: "Remove all images"
      #   script: ./clean.sh
