language: generic

jobs:
  include:
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        install: 
          - pip3 install -r requirements.txt 
        script: 
          - python3 services/rocket/test/rocketApiTest.py
