language: generic

jobs:
  include:
      - stage: "Build all images"
        name: "Building all docker images"
        before_install:
          - chmod +x build.sh
        script: ./build.sh
      - stage: "Docker compose up"
        name: "Launch all docker containers"
        before_install:
          - chmod +x run.sh
        script: ./run.sh
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        before_install:
          - "pip install -U pip"
          - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
        install: 
          - pip install -r requirements.txt
        script:
          - python services/rocketInventory/test/rocketApiTest.py
      - stage: "Docker compose down"
        name: "Stop all docker containers"
        before_install:
          - chmod +x stop.sh
        script: ./stop.sh
      - stage: "Clean up"
        before_install:
          - chmod +x clean.sh
        name: "Remove all images"
        script: ./clean.sh
