jobs:
  include:
      - language: python
      - stage: "Rocket Service units tests"
        name: "Units tests of rocket service"
        script:
          - cd services/rocket

      - stage: "Payload Service units tests"
        name: "Units tests of payload service"
        script:
          - cd services/payload
