language: generic

jobs:
  include:
      - stage: "Building and Launching"
        name: "Building all docker images and launching them"
        script: 
          - ./prepare.sh
          - ./stop.sh
