language: generic

jobs:
  include:
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        install: 
          - pip install -r requirements.txt 
        script: 
          - python pythonconfiguration.py
          - python services/rocket/test/rocketApiTest.py
