jobs:
  include:
      - language: python
      - stage: "Rocket Service"
        name: "Units tests of rocket service"
        install: 
          - pip -r requirements.txt 
        script: 
          - python services/rocket/test/rocketApiTest.py
