version: '2.1'

services:

  ########## Services ##########
  
  # weather service (Node JS)
  weather_service:
    image: djotiham/weather_service
    container_name: weather_service
    expose:
      - "3000"
    ports:
      - "3000:3000"

  # rocket inventory service (Python)
  rocket_inventory_service:
    image: djotiham/rocket_inventory_service
    container_name: rocket_inventory_service
    expose:
        - "8000"
    ports:
      - "8000:8000"

  ########## rpc ##########
  
  # poll creator (Python)
  pollcreator_rpc:
    image: djotiham/pollcreator_rpc
    container_name: pollcreator_rpc
    network_mode: host
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - weather_service
      - rocket_inventory_service

  ########## CLIs ##########
  
  # elon CLI
  eloncli:
    image: djotiham/eloncli
    container_name: eloncli
    network_mode: host
    volumes:
      - .:/host-elon
    depends_on:
      - rocket_inventory_service
      - pollcreator_rpc
    stdin_open: true
    tty: true
    
  # tory CLI
  torycli:
    image: djotiham/torycli
    container_name: torycli
    network_mode: host
    volumes:
      - .:/host-tory
    depends_on:
      - weather_service
      - pollcreator_rpc
    stdin_open: true
    tty: true
    
  # richard CLI
  richardcli:
    image: djotiham/richardcli
    container_name: richardcli
    network_mode: host
    volumes:
      - .:/host-richard
    depends_on:
      - pollcreator_rpc
    stdin_open: true
    tty: true
