version: '2.1'

services:

  ########## Kafka ##########
  
  #zookeeper
  zookeeper: 
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"
    expose:
      - "2181"
  
  #kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  ########## Services ##########
  
  # weather service (Node JS)
  weather_service:
    image: djotiham/weather_service
    container_name: weather_service
    network_mode: host
    volumes:
      - .:/host-weather_service
    depends_on: 
      - zookeeper
      - kafka
      - pollcreator_rpc
    stdin_open: true
    tty: true

  # launcher service (Python)
  launcher_service:
    image: djotiham/launcher_service
    container_name: launcher_service
    network_mode: host
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - delivery_service

  # rocket inventory service (Python)
  rocket_inventory_service:
    image: djotiham/rocket_inventory_service
    container_name: rocket_inventory_service
    network_mode: host
    volumes:
      - .:/host-rocket_inventory_service
    depends_on: 
      - zookeeper
      - kafka
      - pollcreator_rpc
    stdin_open: true
    tty: true

  # rocket inventory service (Python)
  pollsystem_service:
    image: djotiham/pollsystem_service
    container_name: pollsystem_service
    network_mode: host
    volumes:
      - .:/host-pollsystem_service
    depends_on: 
      - zookeeper
      - kafka
      - pollcreator_rpc
    stdin_open: true
    tty: true

  # delivery service (NodeJs)
  delivery_service:
    image: djotiham/delivery_service
    container_name: delivery_service
    expose:
        - "7000"
    ports:
      - "7000:7000"

  ########## rpc ##########
  
  # poll creator (Python)
  pollcreator_rpc:
    image: djotiham/pollcreator_rpc
    container_name: pollcreator_rpc
    network_mode: host
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    stdin_open: true
    tty: true


  # rocket (Python)
  rocket_first_stage_rpc:
    image: djotiham/rocket_first_stage_rpc
    container_name: rocket_first_stage_rpc
    network_mode: host
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      - pollsystem_service
    stdin_open: true
    tty: true

  # rocket (Python)
  rocket_second_stage_rpc:
    image: djotiham/rocket_second_stage_rpc
    container_name: rocket_second_stage_rpc
    network_mode: host
    expose:
      - "8889"
    ports:
      - "8889:8889"
    depends_on:
      - pollsystem_service
      - rocket_first_stage_rpc
    stdin_open: true
    tty: true

  # payload (Python)
  payload_rpc:
    image: djotiham/payload_rpc
    container_name: payload_rpc
    network_mode: host
    expose:
      - "8282"
    ports:
      - "8282:8282"
    depends_on:
      - launcher_service
      - delivery_service
    stdin_open: true
    tty: true

  ########## Servers Socket ########## 
  
  # payload telemetry socket (Python)
  payload_telemetry_server:
    image: djotiham/payload_telemetry_server
    container_name: payload_telemetry_server
    network_mode: host
    volumes:
      - .:/host-payload_telemetry_server
    depends_on:
      - launcher_service
      - delivery_service
    stdin_open: true
    tty: true

  # rocket telemetry socket (Python)
  rocket_telemetry_server:
    image: djotiham/rocket_telemetry_server
    container_name: rocket_telemetry_server
    network_mode: host
    volumes:
      - .:/host-rocket_telemetry_server
    depends_on:
      - delivery_service
      - launcher_service
    stdin_open: true
    tty: true

  ########## Dashboards ##########
  
  # gwynne dashboard
  gwynne_dashboard:
    image: djotiham/gwynne_dashboard
    container_name: gwynne_dashboard
    network_mode: host
    volumes:
      - .:/host-gwynnedashboard
    depends_on:
      - payload_telemetry_server
    stdin_open: true
    tty: true

  # jeff dashboard
  jeff_dashboard:
    image: djotiham/jeff_dashboard
    container_name: jeff_dashboard
    network_mode: host
    volumes:
      - .:/host-jeffdashboard
    depends_on:
      - rocket_telemetry_server
    stdin_open: true
    tty: true
      
  ########## CLIs ##########
  
  # elon CLI
  eloncli:
    image: djotiham/eloncli
    container_name: eloncli
    network_mode: host
    volumes:
      - .:/host-elon
    depends_on:
      - rocket_inventory_service
      - pollcreator_rpc
    stdin_open: true
    tty: true
    
  # tory CLI
  torycli:
    image: djotiham/torycli
    container_name: torycli
    network_mode: host
    volumes:
      - .:/host-tory
    depends_on:
      - weather_service
      - pollcreator_rpc
    stdin_open: true
    tty: true
    
  # richard CLI
  richardcli:
    image: djotiham/richardcli
    container_name: richardcli
    network_mode: host
    volumes:
      - .:/host-richard
    depends_on:
      - pollcreator_rpc
    stdin_open: true
    tty: true
  
  # gwynne CLI
  gwynnecli:
    image: djotiham/gwynne_cli
    container_name: gwynne_cli
    network_mode: host
    volumes:
      - .:/host-gwynne
    depends_on:
      - delivery_service
    stdin_open: true
    tty: true

  ########## Tests ##########
  
  # test scénario 1
  tests1:
    image: djotiham/tests
    container_name: tests
    network_mode: host
    volumes:
      - .:/host-tests
    depends_on:
      - rocket_inventory_service
      - pollcreator_rpc
      - rocket_first_stage_rpc
      - rocket_second_stage_rpc
      - payload_rpc
      - payload_telemetry_server
      - rocket_telemetry_server
      - delivery_service
      - launcher_service 
      - weather_service
    stdin_open: true
    tty: true

  unit_tests:
    image: djotiham/unit_tests
    container_name: unit_tests
    network_mode: host
    volumes:
      - .:/host-unit_tests
    depends_on:
      - rocket_inventory_service
      - pollcreator_rpc
      - rocket_first_stage_rpc
      - rocket_second_stage_rpc
      - payload_rpc
      - payload_telemetry_server
      - rocket_telemetry_server
      - delivery_service
      - launcher_service 
      - weather_service
    stdin_open: true
    tty: true

      # gwynne dashboard
  # admin:
  #   image: djotiham/admin
  #   container_name: admin
  #   network_mode: host
  #   volumes:
  #     - .:/host-admin
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   stdin_open: true
  #   tty: true

    # gwynne dashboard
  # producer:
  #   image: djotiham/producer
  #   container_name: producer
  #   network_mode: host
  #   volumes:
  #     - .:/host-producer
  #   depends_on:
  #     # - admin
  #     - zookeeper
  #     - kafka
  #   stdin_open: true
  #   tty: true

  # # jeff dashboard
  # consumer1:
  #   image: djotiham/consumer1
  #   container_name: consumer1
  #   network_mode: host
  #   volumes:
  #     - .:/host-consumer1
  #   depends_on:
  #     # - admin
  #     - zookeeper
  #     - kafka
  #     - producer
  #   stdin_open: true
  #   tty: true
