name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run prepare
        run: sh ./prepare.sh
      - name: run test
        run: sh ./run.sh
      - name: run stop
        run: sh ./stop.sh