name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: run prepare
      - run: sh ./prepare.sh